### ISSUE TITLE
not showing up as a dark theme

### ISSUE THREAD

**Issue by mackenza** [Brackets-Themes/Railcasts#1]
@MiguelCastillo I created the new repo.  I copied the railcasts.css from your Brackets-themes repo and it all seems to be working except the background is light.  I don't see in the css where the overall background color is set.  Am I missing something?

**Comment by MiguelCastillo** [comment]
@mackenza So, I guess I wasn't 100% accurate when i said it should just work :/  Try doing

``` css
.CodeMirror-scroll {
    background-color:#202020;
    color:#fff;
}
```

instead of

``` css
.cm-s-railscasts.CodeMirror
{
    background-color: #232323;
    color: #E0E2E4;
}
```
